### PR TITLE
Fix override of logger in request context

### LINKED ISSUE #130: Overwriting the logger in request context
https://github.com/xmidt-org/scytale/blob/c6f24fdff929ee11fe11433b28c7a58ffdd6066a/primaryHandler.go#L309

The logger in the context is being set with certain key values pairs at the place above, but when we added bascule to scytale, the logger was added to the context earlier in the middleware chain using this function:
https://github.com/xmidt-org/scytale/blob/c6f24fdff929ee11fe11433b28c7a58ffdd6066a/primaryHandler.go#L65

Both ultimately use `webpa-common/logging`'s `WithLogger()` function, so the later setting of the logger is overwriting the initial one.  We should probably just set the logger once.  The additional key-value pairs provided in the `logginghttp` call should be added in the earlier logger setting, and then this later one can be removed.

### PR DESCRIPTION
**Pull request by renaz6**
- Updated so the logger is only set once. 
- The additional key-value pairs provided in the logginghttp call are added in the earlier logger setting
- the later logger setting is removed

closes #130

### CODE REVIEW

File: basculeLogging.go [hunk 1]
```diff
@@ -22,11 +27,33 @@ func sanitizeHeaders(headers http.Header) (filtered http.Header) {
...
+// 	return func(delegate http.Handler) http.Handler {
+// 		return http.HandlerFunc(
+// 			func(w http.ResponseWriter, r *http.Request) {
+// 				kvs := []interface{}{"requestHeaders", sanitizeHeaders(r.Header), "requestURL", r.URL.EscapedPath(), "method", r.Method}
+// 				kvs, _ = candlelight.AppendTraceInfo(r.Context(), kvs)
+// 				ctx := r.WithContext(logging.WithLogger(r.Context(), log.With(logger, kvs...)))
+// 				delegate.ServeHTTP(w, ctx)
+// 			})
+// 	}
+// }
```
Comment (kristinapathak) [inline basculeLogging.go:40]: I think this can be deleted 👍 

```suggestion
```

File: basculeLogging.go [hunk 2]
```diff
@@ -22,11 +27,33 @@ func sanitizeHeaders(headers http.Header) (filtered http.Header) {
...
+	if logger == nil {
+		panic("The base Logger cannot be nil")
+	}
+
 	return func(delegate http.Handler) http.Handler {
 		return http.HandlerFunc(
 			func(w http.ResponseWriter, r *http.Request) {
 				kvs := []interface{}{"requestHeaders", sanitizeHeaders(r.Header), "requestURL", r.URL.EscapedPath(), "method", r.Method}
+				if len(lf) > 0 {
+					for _, f := range lf {
```
Comment (kristinapathak) [inline basculeLogging.go:53]: We don't need an `if` check here because if `lf` has a length of 0, the for loop will be skipped over.

One thing I would add is a `nil` check for f...something like this:
```suggestion
				for _, f := range lf {
				    if f != nil {
				    // etc...
```

File: primaryHandler.go [hunk 3]
```diff
@@ -158,7 +157,22 @@ func authChain(v *viper.Viper, logger log.Logger, registry xmetrics.Registry) (a
 		basculehttp.WithEErrorResponseFunc(listener.OnErrorResponse),
 	)
 
-	constructors := []alice.Constructor{setLogger(logger), authConstructor, authEnforcer, basculehttp.NewListenerDecorator(listener)}
+	constructors := []alice.Constructor{setLogger(logger,
+
+		// custom logger func that extracts the intended destination of requests
+		func(kv []interface{}, request *http.Request) []interface{} {
```
Comment (kristinapathak) [inline primaryHandler.go:163]: Does this function require any variables defined in its parent function? I can't see any so I would recommend naming/declaring it outside of this function and then passing it here.

**Review by kristinapathak — COMMENTED** [review]
Looks good! A few small comments/suggestions.

**Review by kristinapathak — APPROVED** [review]
🥳
